### ISSUE TITLE
CSS .is-success is conflicting with bulma framework

### ISSUE THREAD

**Issue by ae0000** [apertureless/vue-password-strength-meter#8]
### Expected Behavior
Styles within this component will not override styles in base framework

### Actual Behavior
The ".is-success" css in ./src/components/PasswordStrengthMeter.vue at line 306 is overriding the base styles in the bulma css framework. 

Could this style be scoped? Or prefixed with Password__strength-meter ?

### Environment
- OS: Linux
- NPM version: 5.3.0
- vue.js version: 2.5.2
- vue-password-strength-meter version: 1.1.0

**Comment by apertureless** [comment]
Well I am not a big fan of scoped styles in shareable components. Because you are then not able to overwrite the styles.

However I will rename the error and success class to match the BEM style. So it should fix it.
Btw, you can also pass your own styles. You have the `errorClass` and `successClass` props where you can pass your own styles.
